language: node_js

before_script:
  - yarn build:design-system

script:
  - yarn flow
  - yarn test --runInBand

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: storybook-static
  repo: dusk-network/dusk-ui-kit
  target_branch: gh-pages
  on:
    branch: master
