language: node_js
os: linux
node_js:
  - lts/* # latest LTS
branches:
  only:
    - master
before_install:
  - yarn config set registry "https://npm.dusk.network:4873"
before_script:
  - yarn sb:build

script:
  - echo "skipping tests"

# jobs:
#   include:
#     - stage: release
#       node_js: lts/*
#       script: skip
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script:
#           - npx semantic-release

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - yarn lerna exec --concurrency 1 "npx --no-install semantic-release -e semantic-release-monorepo" && node -e "require('semantic-release-monorepo-hooks').hookAfterAll()"

  - provider: pages
    skip_cleanup: true
    token: $GITHUB_TOKEN
    local_dir: storybook-static
    repo: dusk-network/dusk-ui-kit
    target_branch: gh-pages
    on:
      branch: master

notifications:
  webhooks: https://chat.dusk.network/hooks/j8w8YcFwMpuFJ7mgZ/a4KFgp9QbwfsyQbaQ6TDJYRZfdegjPT4e6ZjHzZ3gtDr4YDv
