name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.16.0"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@dusk-network"

      - name: Install pnpm
        run: npm i pnpm@latest -g

      - name: Recreate .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN} @dusk-network:registry=https://npm.pkg.github.com
          EOF
        env:
          GITHUB_TOKEN: ${{secrets.GH_PACKAGES_TOKEN}}

      - name: Install Dependencies
        run: pnpm i -r
        env:
          GITHUB_TOKEN: ${{secrets.GH_PACKAGES_TOKEN}}

      - name: Run tests
        run: pnpm test

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests

      - name: Update READMEs
        uses: dineshsonachalam/markdown-autodocs@v1.0.4
        with:
          output_file_paths: "[./packages/atoms/drop-down/README.md, ./packages/atoms/icon/README.md, ./packages/atoms/loading-indicator/README.md, ./packages/atoms/logo/README.md, ./packages/atoms/progress-bar/README.md, ./packages/atoms/rich-text/README.md, ./packages/atoms/text-field/README.md, ./packages/atoms/toggle/README.md, ./packages/helpers/README.md, ./packages/molecules/alert/README.md, ./packages/molecules/breadcrumb/README.md, ./packages/molecules/button/README.md, ./packages/molecules/control/README.md, ./packages/molecules/cta-list/README.md, ./packages/molecules/disclaimer-list/README.md, ./packages/molecules/file-upload/README.md, ./packages/molecules/heading/README.md, ./packages/molecules/menu/README.md, ./packages/molecules/mnemonic/README.md, ./packages/molecules/pagination/README.md, ./packages/molecules/password-strength/README.md, ./packages/organisms/accordion/README.md, ./packages/organisms/card/README.md, ./packages/organisms/cookie-banner/README.md, ./packages/organisms/footer/README.md, ./packages/organisms/form/README.md, ./packages/organisms/hero/README.md, ./packages/organisms/navbar/README.md, ./packages/organisms/search-list/README.md, ./packages/organisms/table/README.md, ./packages/organisms/wizard/README.md]"
          commit_message: "🤖 (auto-commit) updating README files"
          categories: "[code-block]"
