name: Docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@dusk-network"

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Install Dependencies
        run: pnpm i -r --frozen-lockfile
        env:
          REGISTRY_TOKEN: ${{secrets.REGISTRY_TOKEN}}

      - name: Build Docs
        run: pnpm run build
        working-directory: ./docs

      - name: Publish Docs to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          destination_dir: docs
