name: Build and deploy storybook site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: "Build + Deploy storybook"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install git
        run: sudo apt-get update && sudo apt-get install -y git
      - run: yarn config set registry "https://npm.dusk.network:4873"
      - run: yarn
      - run: yarn sb:build
      - name: Run lerna
        run: yarn lerna exec --concurrency 1 "npx --no-install semantic-release -e semantic-release-monorepo" && node -e "require('semantic-release-monorepo-hooks').hookAfterAll()"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_REGISTRY: ${{ secrets.NPM_CONFIG_REGISTRY }}
      - name: 🚀 deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
