name: Storybook
on:
  push:
    branches:
      - main

jobs:
  storybook-deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: storybook
    steps:
      - name: Install pnpm
        run: npm i pnpm@latest -g

      - name: Install Dependencies
        run: pnpm install

      - name: Build Storybook
        run: pnpm run build

      - name: Publish Storybook to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
