name: Storybook

on:
  push:
    paths:
      - ".changeset/**"
      - "storybook/**"
    branches:
      - main

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@dusk-network"

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Install Dependencies
        run: pnpm i -r --frozen-lockfile
        env:
          REGISTRY_TOKEN: ${{secrets.REGISTRY_TOKEN}}

      - name: Build Storybook
        run: export NODE_OPTIONS=--openssl-legacy-provider && pnpm run build
        working-directory: ./storybook

      - name: Publish Storybook to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook/storybook-static
          destination_dir: storybook
